USE sakila;

-- 1. List the number of films per category.
SELECT c.name AS category_name, COUNT(f.film_id) AS number_of_films
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY number_of_films DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_ID, city.city, country.country FROM store AS s
JOIN address AS ad
ON s.address_id = ad.address_id
JOIN city AS city
ON ad.city_id = city.city_id
JOIN country AS country
ON city.country_id =country.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store AS s
JOIN customer AS cust ON s.store_id = cust.store_id
JOIN payment AS p ON cust.customer_id = p.customer_id
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category.
SELECT c.name AS category_name, ROUND(AVG(f.length), 2) AS average_running_time
FROM category AS c
JOIN  film_category AS fc ON c.category_id = fc.category_id
JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.name;
